services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ivoz\Ast\Infrastructure\Persistence\Doctrine\:
    resource: '/opt/irontec/ivozprovider/library/Ivoz/Ast/Infrastructure/Persistence/Doctrine/*'
    tags: [{ name: 'domain.repository'}]

  Ivoz\Cgr\Infrastructure\Persistence\Doctrine\:
    resource: '/opt/irontec/ivozprovider/library/Ivoz/Cgr/Infrastructure/Persistence/Doctrine/*'
    tags: [{ name: 'domain.repository'}]

  Ivoz\Kam\Infrastructure\Persistence\Doctrine\:
    resource: '/opt/irontec/ivozprovider/library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/*'
    tags: [{ name: 'domain.repository'}]

  Ivoz\Provider\Infrastructure\Persistence\Doctrine\:
    resource: '/opt/irontec/ivozprovider/library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/*'
    tags: [{ name: 'domain.repository'}]
