Ivoz\Provider\Domain\Model\AdministratorRelPublicSection\AdministratorRelPublicSection:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\AdministratorRelPublicSectionDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: AdministratorRelPublicSections
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
